services:
  qgis:
    build: .
    container_name: qgis-model-firebase
    volumes:
      - /etc/algotour/firebase.json:/root/firebase.json
      - /etc/algotour/riskmaps:/root/riskmaps
      - /etc/algotour/dem:/root/dem
      - ./config.py:/root/config.py
      - ./routes:/root/routes
